// Generated by CoffeeScript 1.4.0
(function() {
  var changeContainer, fadeIn, fadeOut, setup;

  $(document).ready(function() {
    return setup();
  });

  setup = function() {
    $("body").noisy();
    window.currentContainer = $(".home");
    $(".home").css("transform", "translate(0%, 0%)");
    return $("nav a").on("click", changeContainer);
  };

  changeContainer = function(evt) {
    var newContainer;
    evt.preventDefault();
    newContainer = (function() {
      switch ($(this).attr("href")) {
        case "home":
          return $(".home");
        case "about":
          return $(".about");
        case "work":
          return $(".work");
        case "contact":
          return $(".contact");
      }
    }).call(this);
    if (newContainer.selector !== window.currentContainer.selector) {
      return fadeOut(function() {
        window.currentContainer = newContainer;
        return fadeIn();
      });
    }
  };

  fadeOut = function(callback) {
    var container, fadeOutWrapper;
    container = window.currentContainer;
    fadeOutWrapper = function() {
      container.addClass("inactive");
      container.removeClass("active");
      container.css("transform", "translate(150%, 300%)");
      container.off("transitionend", fadeOutWrapper);
      return callback();
    };
    container.on("transitionend", fadeOutWrapper);
    return container.css("transform", "translate(-300%, -500%)");
  };

  fadeIn = function() {
    var container;
    container = window.currentContainer;
    container.removeClass("inactive");
    container.addClass("active");
    return window.setTimeout((function() {
      return container.css("transform", "translate(0%, 0%)");
    }), 5);
  };

}).call(this);
